package afan.GUI;

import fr.ign.cogit.roc4j.graphics.RocSpace;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.XYChart;
import org.knowm.xchart.XYChartBuilder;

import javax.swing.*;

import static javax.swing.UIManager.setLookAndFeel;

/**
 * 用於創建主介面
 * @author Afan Chen
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form mainGUI
     */
    public Main() {

        try {
            setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        setTitle("Afan");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_FileData = new javax.swing.JTextArea();
        jScrollPane_FScoreLine = new javax.swing.JScrollPane();
        jPanel_FScore = new XChartPanel<>(new XYChartBuilder().height(400).width(630).xAxisTitle("Combination").yAxisTitle("FScore").build());
        jScrollPane_ROCCurve = new javax.swing.JScrollPane();
        jPanel_ROCCurve = new RocSpace();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_OutputData = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_ImportCSVFile = new javax.swing.JMenuItem();
        jMenuItem_ImportTSVFileButton = new javax.swing.JMenuItem();
        jMenu_View = new javax.swing.JMenu();
        jMenu_Export = new javax.swing.JMenu();
        jMenuItem_Export = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(new java.awt.Color(0, 153, 153));
        setSize(new java.awt.Dimension(1500, 800));

        jPanel1.setBackground(new java.awt.Color(253, 251, 172));

        jTextArea_FileData.setBackground(new java.awt.Color(252, 250, 201));
        jTextArea_FileData.setColumns(20);
        jTextArea_FileData.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        jTextArea_FileData.setRows(5);
        jScrollPane1.setViewportView(jTextArea_FileData);

        jScrollPane_FScoreLine.setBackground(new java.awt.Color(252, 250, 201));
        jScrollPane_FScoreLine.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel_FScoreLayout = new javax.swing.GroupLayout(jPanel_FScore);
        jPanel_FScore.setLayout(jPanel_FScoreLayout);
        jPanel_FScoreLayout.setHorizontalGroup(
                jPanel_FScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 628, Short.MAX_VALUE)
        );
        jPanel_FScoreLayout.setVerticalGroup(
                jPanel_FScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 398, Short.MAX_VALUE)
        );

        jScrollPane_FScoreLine.setViewportView(jPanel_FScore);

        jScrollPane_ROCCurve.setBackground(new java.awt.Color(252, 250, 201));

        javax.swing.GroupLayout jPanel_ROCCurveLayout = new javax.swing.GroupLayout(jPanel_ROCCurve);
        jPanel_ROCCurve.setLayout(jPanel_ROCCurveLayout);
        jPanel_ROCCurveLayout.setHorizontalGroup(
                jPanel_ROCCurveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 532, Short.MAX_VALUE)
        );
        jPanel_ROCCurveLayout.setVerticalGroup(
                jPanel_ROCCurveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 398, Short.MAX_VALUE)
        );

        jScrollPane_ROCCurve.setViewportView(jPanel_ROCCurve);

        jTabbedPane1.setBackground(new java.awt.Color(253, 251, 172));
        jTabbedPane1.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N

        jTable_OutputData.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane4.setViewportView(jTable_OutputData);

        jTabbedPane1.addTab("ROC", jScrollPane4);

        jTable2.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane5.setViewportView(jTable2);

        jTabbedPane1.addTab("Logistic Regression", jScrollPane5);

        jTable3.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane6.setViewportView(jTable3);

        jTabbedPane1.addTab("Support Vector Machine", jScrollPane6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTabbedPane1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane_FScoreLine, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane_ROCCurve, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane_ROCCurve)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jScrollPane_FScoreLine))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(13, Short.MAX_VALUE))
        );

        jMenu_File.setText("File");
        jMenu_File.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N

        jMenuItem_ImportCSVFile.setText("ImportCSVFile");
        jMenuItem_ImportCSVFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ImportCSVFileActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_ImportCSVFile);

        jMenuItem_ImportTSVFileButton.setText("ImportTSVFile");
        jMenuItem_ImportTSVFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ImportTSVFileButtonActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_ImportTSVFileButton);

        jMenuBar1.add(jMenu_File);

        jMenu_View.setText("View");
        jMenu_View.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu_View);

        jMenu_Export.setText("Export");
        jMenu_Export.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N

        jMenuItem_Export.setText("Export");
        jMenuItem_Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ExportActionPerformed(evt);
            }
        });
        jMenu_Export.add(jMenuItem_Export);

        jMenuBar1.add(jMenu_Export);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    public void updateFScore(XYChart chart){
        jPanel_FScore=new XChartPanel<>(chart);
        jPanel_FScore.repaint();
        jPanel_FScore.revalidate();
        jPanel_FScore.updateUI();
    }

    public void setJTextArea_FileDataText(String s){
        jTextArea_FileData.setText(s);
    }

    public RocSpace getROCSpace(){
        return jPanel_ROCCurve;
    }

    public void updateROC(){
        jPanel_FScore.repaint();
        jPanel_FScore.revalidate();
        jPanel_ROCCurve.updateUI();
    }

    private void jMenuItem_ImportCSVFileActionPerformed(java.awt.event.ActionEvent evt) {
        //讓其他頁面可以進行改動
        var csv=new ImportCSVFile(this);
        csv.setAlwaysOnTop(true);
        csv.setVisible(true);
    }

    private void jMenuItem_ImportTSVFileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //讓其他頁面可以進行改動
        var tsv=new ImportTSVFile(this);
        tsv.setAlwaysOnTop(true);
        tsv.setVisible(true);
    }

    private void jMenuItem_ExportActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Export;
    private javax.swing.JMenuItem jMenuItem_ImportCSVFile;
    private javax.swing.JMenuItem jMenuItem_ImportTSVFileButton;
    private javax.swing.JMenu jMenu_Export;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JMenu jMenu_View;
    private javax.swing.JPanel jPanel1;
    private XChartPanel<XYChart> jPanel_FScore;
    public RocSpace jPanel_ROCCurve;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane_FScoreLine;
    private javax.swing.JScrollPane jScrollPane_ROCCurve;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable_OutputData;
    private javax.swing.JTextArea jTextArea_FileData;
    // End of variables declaration
}
