
import static javax.swing.UIManager.setLookAndFeel;
import javax.swing.UnsupportedLookAndFeelException;
import java.io.FileNotFoundException;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author Afan Chen
 */
public class ImportFile extends javax.swing.JFrame {

    /**
     * Creates new form ImportFile
     */
    public ImportFile() {
        try {
            setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        setTitle("Import File");
        java.awt.Dimension scr_size =java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((scr_size.width - 425) / 2,(scr_size.height - 445) / 2);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FilePicker = new javax.swing.JButton();
        FilePath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MinimumAUC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Import = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jLabel1.setText("File Path");

        FilePicker.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        FilePicker.setText("File Picker");
        FilePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilePickerActionPerformed(evt);
            }
        });

        FilePath.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        FilePath.setText("C:\\Users\\Documents");

        jLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jLabel2.setText("Minimum AUC :");

        MinimumAUC.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        MinimumAUC.setText("0.5");

        jLabel3.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jLabel3.setText("Setting");

        Import.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        Import.setText("Import");
        Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(57, 57, 57)
                                                .addComponent(MinimumAUC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Import)
                                                        .addComponent(FilePicker))))
                                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(FilePicker)
                                        .addComponent(FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(MinimumAUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                                .addComponent(Import)
                                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>

    private void FilePickerActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        DataBase.csvFile = new TSVFile();
        DataBase.csvFile.ChooseFile();//得到檔案位置
        FilePath.setText(DataBase.csvFile.path);
    }

    private void ImportActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        DataBase.minAUC=Double.parseDouble(MinimumAUC.getText());

        if(FilePath.getText().contains(".tsv")) {
            try {
                DataBase.csvFile.GetTSVFileData(FilePath.getText());//取得csv中資料
                DataBase.csvFile.ArrayListDataToArray();
                DataBase.DataPath=FilePath.getText();
                DataBase.ROC = new ROCcurve();
                DataBase.ROC.CutOffPoint(DataBase.csvFile.IntLabelMat,DataBase.csvFile.doubleData,Double.parseDouble(MinimumAUC.getText()));
                DataBase.ROC.FilterData(DataBase.csvFile.doubleData);
                Main.gui.AlreadyImportFile(FilePath.getText());
                /**
                 * 如果讀好資料就關掉jframe，沒有就跳掉不關
                 */
                ImportFile f = this;
                f.dispose();
            } catch (FileNotFoundException e) {
                FilePath.setText("File Not Found");
                e.printStackTrace();
            } catch (IOException e) {
                FilePath.setText("Can't read the file.Please follow the format.");
                e.printStackTrace();
            }
            DataBase.csvFile.ArrayListDataToArray();
        }else{
            FilePath.setText("Please choose .csv file.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    protected javax.swing.JTextField FilePath;
    public javax.swing.JButton FilePicker;
    public javax.swing.JButton Import;
    protected javax.swing.JTextField MinimumAUC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration
}